/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mh.gui;

import com.mh.utils.Utils;
import java.io.File;

import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

import javax.swing.ImageIcon;

/**
 *
 * @author dev
 */
public class DialogMonedero extends javax.swing.JDialog {

    ImageIcon moneda = new ImageIcon("monedilla.png");

    /**
     * Creates new form DialogMonedero
     */
    public DialogMonedero(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.jCajaDinero.setText(ExecGUI.jCajaDinero.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCajaDinero = new javax.swing.JTextField();
        jBotonCeroCeroCinco = new javax.swing.JButton();
        jBotonDiezCent = new javax.swing.JButton();
        jBotonVeinteCent = new javax.swing.JButton();
        jBotonCincuentaCent = new javax.swing.JButton();
        jBotonUnEur = new javax.swing.JButton();
        jBotonDosEur = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jCajaDinero.setText("0.0€");
        jCajaDinero.setPreferredSize(new java.awt.Dimension(100, 40));
        jCajaDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCajaDineroActionPerformed(evt);
            }
        });

        jBotonCeroCeroCinco.setBackground(new java.awt.Color(255, 255, 255));
        jBotonCeroCeroCinco.setForeground(new java.awt.Color(0, 0, 0));
        jBotonCeroCeroCinco.setText("0.05€");
        jBotonCeroCeroCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonCeroCeroCincoActionPerformed(evt);
            }
        });

        jBotonDiezCent.setBackground(new java.awt.Color(255, 255, 255));
        jBotonDiezCent.setForeground(new java.awt.Color(0, 0, 0));
        jBotonDiezCent.setText("0.10€");
        jBotonDiezCent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonDiezCentActionPerformed(evt);
            }
        });

        jBotonVeinteCent.setBackground(new java.awt.Color(255, 255, 255));
        jBotonVeinteCent.setForeground(new java.awt.Color(0, 0, 0));
        jBotonVeinteCent.setText("0.20€");
        jBotonVeinteCent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonVeinteCentActionPerformed(evt);
            }
        });

        jBotonCincuentaCent.setBackground(new java.awt.Color(255, 255, 255));
        jBotonCincuentaCent.setForeground(new java.awt.Color(0, 0, 0));
        jBotonCincuentaCent.setText("0.50€");
        jBotonCincuentaCent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonCincuentaCentActionPerformed(evt);
            }
        });

        jBotonUnEur.setBackground(new java.awt.Color(255, 255, 255));
        jBotonUnEur.setForeground(new java.awt.Color(0, 0, 0));
        jBotonUnEur.setText("1€");
        jBotonUnEur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonUnEurActionPerformed(evt);
            }
        });

        jBotonDosEur.setBackground(new java.awt.Color(255, 255, 255));
        jBotonDosEur.setForeground(new java.awt.Color(0, 0, 0));
        jBotonDosEur.setText("2€");
        jBotonDosEur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonDosEurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBotonVeinteCent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBotonCeroCeroCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBotonUnEur))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBotonDiezCent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBotonCincuentaCent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBotonDosEur)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jCajaDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jCajaDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonCeroCeroCinco)
                    .addComponent(jBotonDiezCent))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonVeinteCent)
                    .addComponent(jBotonCincuentaCent))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonUnEur)
                    .addComponent(jBotonDosEur))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        this.jCajaDinero.setEditable(false);
        this.jBotonCeroCeroCinco.setIcon(moneda);
        this.jBotonDiezCent.setIcon(moneda);
        this.jBotonVeinteCent.setIcon(moneda);
        this.jBotonCincuentaCent.setIcon(moneda);
        this.jBotonUnEur.setIcon(moneda);
        this.jBotonDosEur.setIcon(moneda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCajaDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCajaDineroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCajaDineroActionPerformed

    private void jBotonCeroCeroCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonCeroCeroCincoActionPerformed
        // TODO add your handling code here:

        this.jCajaDinero.setText(Double.toString(Utils.redondeoDosDecimales(Double.parseDouble(this.jCajaDinero.getText().substring(0, this.jCajaDinero.getText().length() - 1)) + 0.05)) + "€");
        ExecGUI.jCajaDinero.setText(Double.toString(Utils.redondeoDosDecimales(Double.parseDouble(ExecGUI.jCajaDinero.getText().substring(0, ExecGUI.jCajaDinero.getText().length() - 1)) + 0.05)) + "€");

        try {
            String ruta = "src/com/mh/sounds/moneda.wav";
            AudioInputStream aui = AudioSystem.getAudioInputStream(new File(ruta).getAbsoluteFile());
            try {
                Clip clip = AudioSystem.getClip();
                clip.open(aui);
                clip.start();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jBotonCeroCeroCincoActionPerformed

    private void jBotonDiezCentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonDiezCentActionPerformed
        // TODO add your handling code here:
        this.jCajaDinero.setText(Double.toString(Utils.redondeoDosDecimales(Double.parseDouble(this.jCajaDinero.getText().substring(0, this.jCajaDinero.getText().length() - 1)) + 0.10)) + "€");
        ExecGUI.jCajaDinero.setText(Double.toString(Utils.redondeoDosDecimales(Double.parseDouble(ExecGUI.jCajaDinero.getText().substring(0, ExecGUI.jCajaDinero.getText().length() - 1)) + 0.10)) + "€");
        try {
            String ruta = "src/com/mh/sounds/moneda.wav";
            AudioInputStream aui = AudioSystem.getAudioInputStream(new File(ruta).getAbsoluteFile());
            try {
                Clip clip = AudioSystem.getClip();
                clip.open(aui);
                clip.start();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jBotonDiezCentActionPerformed

    private void jBotonVeinteCentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonVeinteCentActionPerformed
        // TODO add your handling code here:
        this.jCajaDinero.setText(Double.toString(Utils.redondeoDosDecimales(Double.parseDouble(this.jCajaDinero.getText().substring(0, this.jCajaDinero.getText().length() - 1)) + 0.20)) + "€");
        ExecGUI.jCajaDinero.setText(Double.toString(Utils.redondeoDosDecimales(Double.parseDouble(ExecGUI.jCajaDinero.getText().substring(0, ExecGUI.jCajaDinero.getText().length() - 1)) + 0.20)) + "€");
        try {
            String ruta = "src/com/mh/sounds/moneda.wav";
            AudioInputStream aui = AudioSystem.getAudioInputStream(new File(ruta).getAbsoluteFile());
            try {
                Clip clip = AudioSystem.getClip();
                clip.open(aui);
                clip.start();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jBotonVeinteCentActionPerformed

    private void jBotonCincuentaCentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonCincuentaCentActionPerformed
        // TODO add your handling code here:
        this.jCajaDinero.setText(Double.toString(Utils.redondeoDosDecimales(Double.parseDouble(this.jCajaDinero.getText().substring(0, this.jCajaDinero.getText().length() - 1)) + 0.50)) + "€");
        ExecGUI.jCajaDinero.setText(Double.toString(Utils.redondeoDosDecimales(Double.parseDouble(ExecGUI.jCajaDinero.getText().substring(0, ExecGUI.jCajaDinero.getText().length() - 1)) + 0.50)) + "€");
        try {
            String ruta = "src/com/mh/sounds/moneda.wav";
            AudioInputStream aui = AudioSystem.getAudioInputStream(new File(ruta).getAbsoluteFile());
            try {
                Clip clip = AudioSystem.getClip();
                clip.open(aui);
                clip.start();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jBotonCincuentaCentActionPerformed

    private void jBotonUnEurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonUnEurActionPerformed
        // TODO add your handling code here:
        this.jCajaDinero.setText(Double.toString(Utils.redondeoDosDecimales(Double.parseDouble(this.jCajaDinero.getText().substring(0, this.jCajaDinero.getText().length() - 1)) + 1.0)) + "€");
        ExecGUI.jCajaDinero.setText(Double.toString(Utils.redondeoDosDecimales(Double.parseDouble(ExecGUI.jCajaDinero.getText().substring(0, ExecGUI.jCajaDinero.getText().length() - 1)) + 1.0)) + "€");
        try {
            String ruta = "src/com/mh/sounds/moneda.wav";
            AudioInputStream aui = AudioSystem.getAudioInputStream(new File(ruta).getAbsoluteFile());
            try {
                Clip clip = AudioSystem.getClip();
                clip.open(aui);
                clip.start();
                
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jBotonUnEurActionPerformed

    private void jBotonDosEurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonDosEurActionPerformed
        // TODO add your handling code here:
        this.jCajaDinero.setText(Double.toString(Utils.redondeoDosDecimales(Double.parseDouble(this.jCajaDinero.getText().substring(0, this.jCajaDinero.getText().length() - 1)) + 2.0)) + "€");
        ExecGUI.jCajaDinero.setText(Double.toString(Utils.redondeoDosDecimales(Double.parseDouble(ExecGUI.jCajaDinero.getText().substring(0, ExecGUI.jCajaDinero.getText().length() - 1)) + 2.0)) + "€");
        try {
            String ruta = "src/com/mh/sounds/moneda.wav";
            AudioInputStream aui = AudioSystem.getAudioInputStream(new File(ruta).getAbsoluteFile());
            try {
                Clip clip = AudioSystem.getClip();
                clip.open(aui);
                clip.start();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jBotonDosEurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogMonedero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogMonedero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogMonedero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogMonedero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogMonedero dialog = new DialogMonedero(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonCeroCeroCinco;
    private javax.swing.JButton jBotonCincuentaCent;
    private javax.swing.JButton jBotonDiezCent;
    private javax.swing.JButton jBotonDosEur;
    private javax.swing.JButton jBotonUnEur;
    private javax.swing.JButton jBotonVeinteCent;
    private javax.swing.JTextField jCajaDinero;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
